AWSTemplateFormatVersion: '2010-09-09'
Description: 'Rearc Quest S3 and Lambda Infrastructure as Code'

Resources:
  #S3 Bucket
  S3BucketBucketrearcquestmmorris:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "bucket-rearc-quest-mmorris"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: false
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      Tags:
      - Value: "rearc-quest"
        Key: "resource-group"

  LambdaFunctionFunctionrearcquestmmorrisingestbls:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      Handler: "lambda_function.lambda_handler"
      Code:
        ZipFile: |
          import json
          import boto3
          
          def lambda_handler(event, context):
              print(f"Received event: {json.dumps(event)}")
              
              # Your Lambda logic here
              s3_client = boto3.client('s3')
              
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Role: "arn:aws:iam::054178830715:role/rearc-quest-lambda-basic-execution-role"
      FileSystemConfigs: []
      FunctionName: "function-rearc-quest-mmorris-ingest-bls"
      Runtime: "python3.13"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/function-rearc-quest-mmorris-ingest-bls"
      EphemeralStorage:
        Size: 512
      Tags:
      - Value: "rearc-quest"
        Key: "resource-group"
      Architectures:
      - "x86_64"
